### ISSUE TITLE
Metadata only option

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/breaker#10]
Is there an option in breaker to just generate the meta.yaml?  It's ultimately all that the ATLAS team need, and they are a bit concerned that the simple generation of this file may not happen because breaker is waiting for a (maybe non-existent or broken) map from GraceDB.  They are also worried that while we might be trying to get them a simple text file, the maps my fill the destination directory before the text file is ready.

**Comment by thespacedoctor** [comment]
Metadata file is generated first before maps are downloaded. It is even generated if no maps are available to download. As long as breaker is connected to gracedb and rsync running then we’re all good.
